### ISSUE TITLE
Incompatible with Mantis BT 1.2.19?!

### ISSUE THREAD

**Issue by cljk** [bueltge/Markdown-for-MantisBT#5]
Installed the Plugin in my freshly installed Mantis 1.2.19 - and the pluginmanager says "unmet dependencies "MantisBT Core 1.2.0, 1.3.0"

I´m not fit enough yet in Mantis to solve this on my own.... 
Perhaps it´s a minor issue in the configuration.

![manage plugins - mantisbt - google chrome 2015-10-09 09 32 40](https://cloud.githubusercontent.com/assets/654602/10388265/bd9070c4-6e68-11e5-8eb1-d7f8cf1100ec.png)

**Comment by cljk** [comment]
Okay.... found the solution on my own ;-)

Changing in ``Markdown.php`` 
```
$this->requires    = array(
			'MantisCore'           => '1.2.0, 1.3.0',
			'MantisCoreFormatting' => '1.0a',
		);
```

to

```
$this->requires    = array(
                        'MantisCore'           => '1.2.0',
                        'MantisCoreFormatting' => '1.0a',
                );
```
works just fine... but is perhaps not indended....

**Comment by bueltge** [comment]
Hm, not really fine. I don't understand really what Mantis here checks. :(

**Comment by cljk** [comment]
Obviously, what version of the Mantis core is needed for the plugin - as string. And the string 
```
'1.2.0, 1.3.0'
```
is not recognized as array but as unknown version. So the solution for me was to replace it with
```
'1.2.0'
```

**Comment by bueltge** [comment]
But I have  second install, that run with the 1.3* Beta and then is it not working. :(
I have search in other plugins and I found this solution, two strings, separated with comma.

**Comment by cljk** [comment]
Perhaps the comma-separation is a new feature of 1.3 and incompatible with 1.2?!
Is the version-string '1.2.0' compatible with 1.3 Beta?

**Comment by bueltge** [comment]
Right, the comma seperated strings works in 1.3*. For my logic is the 1.2 enough, it works since 1.2* and higher, but MantisBT 1.3* will not check this.

**Comment by hamx0r** [comment]
I've proposed another syntax which should work on both 1.2 and 1.3 in pull request #9 and issue #10
