### ISSUE TITLE
Bugs for Mantis 1.3.0-rc1-dev

### ISSUE THREAD

**Issue by KtuluWU** [bueltge/Markdown-for-MantisBT#7]
**Hello,** 

Thank you for your plugin.
I found some bugs for our Mantisbt on version 1.3.0-rc1-dev.

The bugs are as follow:
- Lists (bulleted or not), either need to be the first thing in the note, to be on the line after a title or to be the only markdown of the note:

![1](https://cloud.githubusercontent.com/assets/17195210/15387953/e98dd206-1daf-11e6-88be-58c6bcf566ef.png)
- Titles show strange behaviors:

![2](https://cloud.githubusercontent.com/assets/17195210/15387949/e5d7006a-1daf-11e6-88ba-ae9ab706e884.jpg)
- Quotes don't seem to work:

![3](https://cloud.githubusercontent.com/assets/17195210/15387973/faef88d2-1daf-11e6-828a-8090e8414a0f.png)

Waiting for your answer :)
Thank you very much !

**Comment by bueltge** [comment]
Thanks for the issue, I will check this in my 1.3 dev install to solve this problems.

**Comment by KtuluWU** [comment]
Thanks for your answer.
We have a lot of plugins actives in our mantis, and I found theses bugs with the BBCodePlus.
If BBCodePlus is disable, the Markdown works. I think that the BBCodeplus has some bugs, so sorry for disturbing.

**Comment by bueltge** [comment]
Thanks for the news.
